image: docker:latest

services:
    - docker:dind

stages:
    - build
    - test
    - deploy
build:
    stage: build
    only:
        - develop
    before_script:
        - chmod -R 777 .
        - chmod +x ./docker/scripts/setup_env.sh
        - ./docker/scripts/setup_env.sh
    script:
        - docker-compose -f docker-compose-deploy.yml build --force-rm

test:
    stage: test
    only:
        - develop
    before_script:
        - chmod -R 777 .
        - chmod +x ./docker/scripts/setup_env.sh
        - ./docker/scripts/setup_env.sh
    script:
        - docker-compose -f docker-compose-deploy.yml run app pytest -k TestAccount

deploy:
    stage: deploy
    only:
        - develop
    before_script:
        - chmod -R 777 .
        - chmod +x ./docker/scripts/setup_env.sh
        - ./docker/scripts/setup_env.sh
    script:
        - docker-compose -f docker-compose-deploy.yml up -d


