image: docker:latest

services:
    - docker:dind

stages:
    - test

test:
    stage: test
    only:
        - feature/docker-deploy-certbot
    script:
        - docker-compose --version
        - docker-compose -f docker-compose-deploy.yml up -d --build


