image: docker:latest

services:
    - docker:dind

stages:
    - app-deploy

app-deploy:
    stage: app-deploy
    only:
        - develop
    before_script:
        - chmod +x ./docker/scripts/setup_env.sh
        - ./docker/scripts/setup_env.sh
    script:
        - docker-compose --version
        - docker-compose -f docker-compose-deploy.yml up -d --build


