version: '3.7'
services:
  app:
    container_name: dev_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    env_file: .env
    volumes:
      - static_volume:/vol/web
      - socket_dir:/var/run
    depends_on:
      - gulp
      - db
  proxy:
    container_name: dev_proxy
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - static_volume:/vol/static
      - socket_dir:/var/run
      - ./docker/certbot/www:/vol/certbot:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - gulp
  db:
    container_name: dev_db
    image: postgres:14-alpine
    restart: on-failure
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  gulp:
    container_name: dev_gulp
    build:
      context: ./
      dockerfile: ./docker/gulp/Dockerfile
    command: gulp buildStyles
    restart: "no"
    volumes:
      - static_volume:/app/static
  certbot:
    image: certbot/certbot:latest
    container_name: dev_certbot
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
  postgres_data:
  socket_dir: