version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.21.6
    volumes:
      - ./docker/nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: dev_backend
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    restart: always
    env_file: .env
    command: gunicorn RecipeRemix.wsgi:application --bind 0.0.0.0:5000
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
     - gulp
  db:
    container_name: dev_db
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  gulp:
    container_name: dev_gulp
    build:
      context: ./
      dockerfile: ./docker/gulp/Dockerfile
    command: gulp watch
    volumes:
      - .:/app
volumes:
  static_volume:
  postgres_data: