version: '3.7'
services:
  app:
    container_name: dev_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    restart: always
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/vol/app
      - socket:/recipe_remix.sock
    depends_on:
      - db
      - gulp
  proxy:
    container_name: dev_proxy
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/proxy/Dockerfile
    volumes:
      - static_volume:/vol/static
      - socket:/recipe_remix.sock
    ports:
      - "80:80"
    depends_on:
      - app
  db:
    container_name: dev_db
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  gulp:
    container_name: dev_gulp
    build:
      context: ./
      dockerfile: ./docker/gulp/Dockerfile
    command: gulp watch
    volumes:
      - .:/app
volumes:
  static_volume:
  postgres_data: