#!/bin/bash

echo DATABASE_NAME=$DATABASE_NAME >> .env
echo DATABASE_PASS=$DATABASE_PASS >> .env
echo DATABASE_HOST=$DATABASE_HOST >> .env
echo DATABASE_PORT=$DATABASE_PORT >> .env
echo DATABASE_USER=$DATABASE_USER >> .env
echo DEBUG=$DEBUG >> .env
echo POSTGRES_USER=$POSTGRES_USER >> .env
echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
echo POSTGRES_DB=$POSTGRES_DB >> .env
